services:
    postgres:
        image: postgres:16
        container_name: employees-postgres
        restart: unless-stopped
        environment:
            POSTGRES_USER: appuser
            POSTGRES_PASSWORD: secretpassword
            POSTGRES_DB: employees_db
        ports:
            - "5432:5432"
        volumes:
            - postgres-employees-data:/var/lib/postgresql/data

    pgadmin:
        image: dpage/pgadmin4
        container_name: employees-pgadmin
        restart: unless-stopped
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@example.com
            PGADMIN_DEFAULT_PASSWORD: admin
        ports:
            - "5050:80"
        depends_on:
            - postgres

volumes:
    postgres-employees-data: